// GENERATED by scripts/build-apps.mjs - do not edit
export function doGet(e: GoogleAppsScript.Events.DoGet): GoogleAppsScript.HTML.HtmlOutput {
  const page = e && e.parameter && e.parameter.page ? String(e.parameter.page).trim() : '';

  if (page === 'dashboard') {
    return HtmlService.createHtmlOutputFromFile('dashboard');
  }
  if (page === 'hola') {
    return HtmlService.createHtmlOutputFromFile('hola');
  }
  if (page === 'home') {
    return HtmlService.createHtmlOutputFromFile('home');
  }

  return HtmlService.createHtmlOutputFromFile('home');
}
