// GENERATED by scripts/build-apps.mjs - do not edit
export function doGet(e: GoogleAppsScript.Events.DoGet): GoogleAppsScript.HTML.HtmlOutput {
  const page = (e && e.parameter && e.parameter.page ? String(e.parameter.page) : '').trim();
  const known = new Set(["dashboard","hola","home"]);
  const target = known.has(page) ? page : 'home';
  return HtmlService.createHtmlOutputFromFile(target);
}
